version: '2.1'

volumes:
  cups:
  avahi:

services:
  cups:
    build: ./cups
    network_mode: host
    ports:
     - "80"
     - "631"
    volumes:
     - 'cups:/etc/cups'
    privileged: true
    restart: always
  avahi:
    build: ./avahi
    network_mode: host
    ports:
     - "5353:5353/udp"
    volumes:
     - 'avahi:/etc/avahi'
    privileged: true
    restart: always
