version: '2.1'

volumes:
  cups:
  avahi:

services:
  cups:
    build: ./cups
    network_mode: host
    volumes:
     - 'avahi:/etc/avahi'
     - 'cups:/etc/cups'
    privileged: true
    restart: always
  avahi:
    build: ./avahi
    network_mode: host
    depends_on:
    - cups
    volumes:
     - 'avahi:/etc/avahi'
     - 'cups:/etc/cups'
    privileged: true
    restart: always
