version: '2.1'

volumes:
  cups:
  avahi:

services:
  airprint:
    build: ./airprint
    network_mode: host
    expose:
     - "53"
     - "80"
     - "631"
     - "5353"
    volumes:
     - 'cups:/etc/cups'
     - 'avahi:/etc/avahi'
    privileged: true
    restart: always
