version: '2.1'

volumes:
  cups:
  avahi:

services:
  airprint:
    build: ./airprint
    network_mode: host
    ports:
     - "53:53/tcp"
     - "53:53/udp"
     - "80"
     - "631"
     - "5353:5353/udp"
    volumes:
     - 'cups:/etc/cups'
     - 'avahi:/etc/avahi'
    privileged: true
    restart: always
